version: "3.8"
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfiles/nginx.Dockerfile
    ports:
      - '8000:80'
    # volumes:
    #   - ./src:/var/www/html
    #   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - database
      
  php:
    build: 
      context: .
      dockerfile: Dockerfiles/php.Dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  database:
    image: mysql:5.7
    env_file:
      - ./envfile/database.env
  composer:
    build: 
      context: ./Dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build: 
      context: .
      dockerfile: Dockerfiles/php.Dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/vaw/www/html/artisan"]
  npm:
    build: 
      context: ./Dockerfiles
      dockerfile: npm.dockerfile
    volumes:
      - ./src:/var/www/html