version: "3.9"
services:
  server:
    image: 'nginx:stable-alphine'
    ports:
      - '8080:80'
    volumes:
      - /nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      -  
  php:
    image: 
      context: ./Dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:
  database:
    image: mysql:5.7
    env_file:
      - ./envfile/database.env
 